# Cohort Split

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [11]:
df = pd.read_csv("data/restructured_data.csv")
df.head()

,LOG_ID,MRN,hypoxemia,crp,co2,glucose,hematocrit,hemoglobin,leukocytes,potassium,sodium,pH,lactate,age,sex,bmi,height,weight
0,0004678c0906bb9e,6b03d87f76b29311,0,7.6,23.0,119.0,27.8,9.2,6.2,4.4,130.0,NaN,NaN,70,0,24.170546,1.651000,65.884098
1,0011abe1d4cc9915,c28fd59799fdb891,0,NaN,24.0,121.0,26.7,8.4,8.0,4.2,141.0,NaN,NaN,69,0,23.346969,1.778000,73.806400
2,00126ebdaa3f286a,f3ef9a2e287a78e8,0,15.9,27.0,106.0,36.7,12.4,9.8,3.7,141.0,7.42,NaN,83,0,25.200019,1.803400,81.956800
3,0013fc9808033c8f,ef268d8abece3181,0,NaN,26.0,122.0,39.5,14.0,5.7,4.5,137.0,NaN,NaN,79,0,28.384024,1.753221,87.246353
4,001656cc37a919fd,73ae956471950fd0,0,0.3,23.0,96.0,38.7,12.9,8.4,3.8,138.0,NaN,NaN,23,1,35.843942,1.549400,86.048414

In [12]:
# filter all positives 
df_pos_id = df["hypoxemia"] == 1
df_pos = df[df_pos_id]

In [13]:
# sample negatives
RANDOM_STATE = 42
NEG_SAMPLE_SIZE = 200

df_neg_id = df["hypoxemia"] == 0
df_neg = df[df_neg_id]

sample_neg = df_neg.sample(n=NEG_SAMPLE_SIZE, random_state=RANDOM_STATE)

In [14]:
# combine the positives and negatives
sample = pd.concat([df_pos, sample_neg], axis=0)

sample.head(20)

,LOG_ID,MRN,hypoxemia,crp,co2,glucose,hematocrit,hemoglobin,leukocytes,potassium,sodium,pH,lactate,age,sex,bmi,height,weight
3197,217b66269eead504,c2d7642629dd4f77,1,NaN,23.0,135.0,25.0,8.4,18.8,4.6,134.0,7.30,NaN,34,0,47.681440,1.7780,150.734573
3305,2268d745f996ae93,cd2b4ceac15ba6d7,1,NaN,28.0,300.0,25.9,8.1,4.2,4.0,136.0,NaN,NaN,55,0,29.194566,1.7018,84.551061
3489,246f1df22bfd4879,2a78f47ecc3eb13f,1,5.7,21.0,198.0,20.1,7.0,13.8,4.3,130.0,7.35,NaN,82,0,23.967312,1.8288,80.158901
4705,314ed2577c1f82dd,04aeffd955852bdc,1,NaN,28.0,112.0,23.2,7.9,9.0,3.4,149.0,7.45,NaN,51,0,22.160963,1.8034,72.073025
5100,353fc9a27c673b1f,cd2b4ceac15ba6d7,1,NaN,23.0,155.0,30.1,9.7,7.1,3.8,136.0,NaN,NaN,54,0,28.877279,1.7018,83.632160
6630,456f7f604750a789,6fc73583f93d0f51,1,14.6,32.0,136.0,23.4,7.9,7.3,3.2,141.0,NaN,NaN,74,0,15.756966,1.7780,49.812245
7195,4b4ff1b4e68cc458,4cec3a7de55d09f3,1,0.5,25.0,120.0,43.1,14.3,10.9,4.0,141.0,NaN,NaN,83,0,19.252202,1.6764,54.104789
7679,5050dbbd0a8069f6,dca15ef5697b6296,1,NaN,20.0,102.0,35.3,11.4,4.9,4.1,130.0,7.44,NaN,49,0,36.629497,1.7780,115.796242
8152,555fe624a9308a38,777abdf08bed0db5,1,NaN,25.0,141.0,30.3,10.4,10.4,3.4,137.0,NaN,NaN,20,1,27.320816,1.7272,81.504000
9361,62ad47afa3ebe33a,84c6821347ed0c15,1,NaN,30.0,138.0,24.7,8.3,11.1,4.0,137.0,7.26,NaN,40,1,29.786380,1.5748,73.870075
13425,8e801033255debfc,951f998fc5fdc0d8,1,5.1,28.0,98.0,34.6,11.6,6.1,3.5,136.0,NaN,NaN,34,1,43.946381,1.6510,119.789089
18381,c27b0e7ab5a36fdb,84c6821347ed0c15,1,NaN,19.0,172.0,21.8,7.2,16.6,4.9,133.0,7.26,NaN,40,1,29.786380,1.5748,73.870075
18405,c2c42b889f4362a1,aa9cd57a3ec0b99c,1,NaN,19.0,357.0,30.0,10.1,7.1,2.7,141.0,NaN,NaN,30,0,18.931278,1.8796,66.882239
20092,d4bb139f08a8311d,fc984eb9d9165e96,1,NaN,21.0,143.0,35.6,12.1,6.0,4.0,137.0,7.51,NaN,43,1,17.352703,1.5494,41.657600
21028,de8879f99f3ac56f,499386c1a8693fd0,1,15.0,23.0,91.0,31.6,10.4,11.1,3.8,136.0,NaN,NaN,51,0,24.364659,1.8034,79.240000
24043,fe9324aa46382ff5,a1fcee88b4a59390,1,NaN,24.0,106.0,31.3,10.5,5.1,8.3,139.0,NaN,NaN,51,1,30.652612,1.6510,83.552920
3287,224b88036ec409c4,d7fd14948767321f,0,NaN,25.0,158.0,38.7,13.2,7.7,3.8,139.0,NaN,NaN,59,1,44.701012,1.5494,107.311053
14509,999014f088360697,e09f0116cf86f6a4,0,NaN,24.0,110.0,39.0,12.9,13.3,3.8,139.0,7.38,NaN,22,0,23.789324,1.7526,73.071449
4599,30060349f8fd1212,48599ff586ce3238,0,NaN,21.0,176.0,28.9,9.9,12.0,3.9,141.0,7.41,NaN,58,1,48.302149,1.5748,119.789089
5311,376d0fedba9fef52,2082946aa4c30c4c,0,NaN,31.0,95.0,40.0,13.4,7.8,4.8,145.0,NaN,NaN,44,0,27.360714,1.7018,79.240000

In [24]:
# train test (stratified) split
TEST_PROP = 0.25

train_df, test_df = train_test_split(
    sample,
    test_size = TEST_PROP,
    stratify = sample["hypoxemia"],
    random_state = RANDOM_STATE
)

,LOG_ID,MRN,hypoxemia,crp,co2,glucose,hematocrit,hemoglobin,leukocytes,potassium,sodium,pH,lactate,age,sex,bmi,height,weight
2619,1bd85329013f1787,597888edad1e0234,0,NaN,27.0,109.0,40.7,13.7,10.1,3.9,139.0,NaN,NaN,61,0,23.293424,1.734484,70.076743
14509,999014f088360697,e09f0116cf86f6a4,0,NaN,24.0,110.0,39.0,12.9,13.3,3.8,139.0,7.38,NaN,22,0,23.789324,1.752600,73.071449
12490,8448e8d643d10a33,fc7325d97878a4ee,0,3.5,24.0,189.0,21.6,7.7,7.7,3.7,130.0,NaN,NaN,54,0,21.927018,1.600200,56.147200
15141,9fe66c17ea46cb93,c0da4db6ea807dee,0,17.2,31.0,146.0,34.9,11.1,7.6,3.7,139.0,NaN,NaN,75,0,20.852658,1.879600,73.670277
9021,5f0bbceac220c206,0cc04ea4d921b8e4,0,18.1,27.0,83.0,22.3,7.6,11.9,4.0,139.0,7.44,NaN,69,1,29.159189,1.803400,94.833017

In [25]:
train_df.head()

,LOG_ID,MRN,hypoxemia,crp,co2,glucose,hematocrit,hemoglobin,leukocytes,potassium,sodium,pH,lactate,age,sex,bmi,height,weight
24043,fe9324aa46382ff5,a1fcee88b4a59390,1,NaN,24.0,106.0,31.3,10.5,5.1,8.3,139.0,NaN,NaN,51,1,30.652612,1.651000,83.552920
21231,e0b11805971e0b47,e8a373649a8cd136,0,NaN,23.0,146.0,32.6,11.2,5.9,3.4,128.0,NaN,NaN,58,0,22.058319,1.676400,61.990867
20079,d4a0a446061c0bdd,a7141971b7880096,0,NaN,26.0,95.0,36.9,12.1,5.7,4.5,133.0,NaN,NaN,82,0,26.318018,1.828013,87.945080
8152,555fe624a9308a38,777abdf08bed0db5,1,NaN,25.0,141.0,30.3,10.4,10.4,3.4,137.0,NaN,NaN,20,1,27.320816,1.727200,81.504000
16446,ae1ab50b1b2df1da,20d2d5b9d0bc870e,0,11.9,26.0,68.0,18.6,6.2,16.1,2.9,134.0,NaN,NaN,47,0,40.972332,1.750009,125.479087

In [30]:
test_df.head()

,LOG_ID,MRN,hypoxemia,crp,co2,glucose,hematocrit,hemoglobin,leukocytes,potassium,sodium,pH,lactate,age,sex,bmi,height,weight
2619,1bd85329013f1787,597888edad1e0234,0,NaN,27.0,109.0,40.7,13.7,10.1,3.9,139.0,NaN,NaN,61,0,23.293424,1.734484,70.076743
14509,999014f088360697,e09f0116cf86f6a4,0,NaN,24.0,110.0,39.0,12.9,13.3,3.8,139.0,7.38,NaN,22,0,23.789324,1.752600,73.071449
12490,8448e8d643d10a33,fc7325d97878a4ee,0,3.5,24.0,189.0,21.6,7.7,7.7,3.7,130.0,NaN,NaN,54,0,21.927018,1.600200,56.147200
15141,9fe66c17ea46cb93,c0da4db6ea807dee,0,17.2,31.0,146.0,34.9,11.1,7.6,3.7,139.0,NaN,NaN,75,0,20.852658,1.879600,73.670277
9021,5f0bbceac220c206,0cc04ea4d921b8e4,0,18.1,27.0,83.0,22.3,7.6,11.9,4.0,139.0,7.44,NaN,69,1,29.159189,1.803400,94.833017

In [41]:
# outcome counts for train and test set

train_counts = train_df["hypoxemia"].value_counts()
test_counts = test_df["hypoxemia"].value_counts()

split_count = pd.DataFrame({
    "train": train_counts,
    "test": test_counts
}).T.fillna(0).astype(int)

split_count

hypoxemia    0   1
train      150  12
test        50   4